/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "var(--primary, #B7C4FF)",
        "on-primary": "var(--onPrimary, #1B2E70)",
        "primary-container": "var(--primaryContainer, #33448D)",
        "on-primary-container": "var(--onPrimaryContainer, #DEE0FF)",
        "inverse-primary": "var(--inversePrimary, #4759A9)",
        "secondary": "var(--secondary, #C2C5DD)",
        "on-secondary": "var(--onSecondary, #2C2F42)",
        "secondary-container": "var(--secondaryContainer, #424659)",
        "on-secondary-container": "var(--onSecondaryContainer, #DFE1F9)",
        "tertiary": "var(--tertiary, #E5B9D6)",
        "on-tertiary": "var(--onTertiary, #45253C)",
        "tertiary-container": "var(--tertiaryContainer, #5E3B53)",
        "on-tertiary-container": "var(--onTertiaryContainer, #FFD8ED)",
        "background": "var(--background, #131218)",
        "on-background": "var(--onBackground, #E5E1E9)",
        "surface": "var(--surface, #131218)",
        "on-surface": "var(--onSurface, #E5E1E9)",
        "surface-variant": "var(--surfaceVariant, #46464F)",
        "on-surface-variant": "var(--onSurfaceVariant, #C7C5D0)",
        "surface-tint": "var(--surfaceTint, #B7C4FF)",
        "inverse-surface": "var(--inverseSurface, #E5E1E9)",
        "inverse-on-surface": "var(--inverseOnSurface, #302F36)",
        "error": "var(--error, #FFB4AB)",
        "on-error": "var(--onError, #690005)",
        "error-container": "var(--errorContainer, #93000A)",
        "on-error-container": "var(--onErrorContainer, #FFDAD6)",
        "outline": "var(--outline, #90909A)",
        "outline-variant": "var(--outlineVariant, #46464F)",
        "scrim": "var(--scrim, #000000)",
        "surface-bright": "var(--surfaceBright, #3A383F)",
        "surface-dim": "var(--surfaceDim, #131218)",
        "surface-container": "var(--surfaceContainer, #1F1E25)",
        "surface-container-high": "var(--surfaceContainerHigh, #29282F)",
        "surface-container-highest": "var(--surfaceContainerHighest, #34333A)",
        "surface-container-low": "var(--surfaceContainerLow, #1B1A20)",
        "surface-container-lowest": "var(--surfaceContainerLowest, #0D0C12)",
        "filled-tonal-button-content-color": "var(--filledTonalButtonContentColor)",
        "filled-tonal-button-container-color": "var(--filledTonalButtonContainerColor)",
        "filled-tonal-button-disabled-content-color": "var(--filledTonalButtonDisabledContentColor)",
        "filled-tonal-button-disabled-container-color": "var(--filledTonalButtonDisabledContainerColor)",
        "filled-card-content-color": "var(--filledCardContentColor)",
        "filled-card-container-color": "var(--filledCardContainerColor)",
        "filled-card-disabled-content-color": "var(--filledCardDisabledContentColor)",
        "filled-card-disabled-container-color": "var(--filledCardDisabledContainerColor)",
      },
    },
  },
  plugins: [require("daisyui")],
};
