name: Build Module Zip

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '.github/scripts/**'
      - 'webui/**'
      - 'module/**'
      - 'version'

jobs:
  build:
    name: Build Flashable Zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Build WebUI
      working-directory: ./webui
      run: |
        bun install
        bun run build
        cp -r ./dist/* ../module/webroot

    - name: Compile Flashable Zip
      id: compileZip
      run: bash .github/scripts/compile_zip.sh

    - name: Upload Compiled Zip as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Flashable-Zip
        path: net-switch-*.zip